### PR TITLE
fix key error with PING

### PR DESCRIPTION
**Pull request by a16bitsysop**

### CODE REVIEW

**Comment by MAGICCC** [comment]
Is there some known ETA for the merge?

**Comment by DerLinkman** [comment]
@a16bitsysop I hope it´s ok if we use your fix until it is merged into master?

Of course we will credit that :)

**Comment by a16bitsysop** [comment]
@DerLinkman yes thats fine. 3.15 has oletools as well (py3-oletools)

**Comment by DerLinkman** [comment]
Yup, i already tested the olefy with your fix on Alpine 3.15.

Thank you for the fix.

**Comment by c-rosenberg** [comment]
@a16bitsysop thanks a lot. And SORRY for the late response.

**Pull request merged**
